name: loftify
version: 2.5.0+2500
description: An third-party application for LOFTER
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 鎺т欢
  lottie: ^3.1.2 # Lottie
  animations: ^2.0.11 # 鍔ㄧ敾
  fluttertoast: ^8.2.6 # 鍚愬徃
  auto_size_text: ^3.0.0 # 鑷€傚簲鏂囨湰
  flutter_widget_from_html: ^0.15.3 # 灏咹TML娓叉煋鎴愮粍浠?
  card_swiper: ^3.0.1 # 鍗＄墖婊戝姩
  modal_bottom_sheet: ^3.0.0 # 搴曢儴寮圭獥
  video_player: ^2.9.1 # 瑙嗛鎾斁
  #  video_player_media_kit: ^1.0.5 # 瑙嗛鎾斁
  #  media_kit_libs_windows_video: ^1.0.9
  like_button: ^2.0.5 # 鐐硅禐鎸夐挳
  sliding_up_panel: ^2.0.0+1 # 婊戝姩闈㈡澘
  blur: ^3.1.0 # 妯＄硦
  path_drawing: ^1.0.1
  awesome_chewie:
    path: third-party/chewie
  flutter_inappwebview: ^6.0.0 # Webview
  extended_nested_scroll_view: ^6.2.1 # 宓屽婊氬姩
  # 绯荤粺
  provider: ^6.0.5 # 鐘舵€佺鐞?
  local_auth: ^2.2.0 # 鎸囩汗楠岃瘉
  local_auth_android: ^1.0.42 # 鎸囩汗楠岃瘉
  package_info_plus: ^8.0.0 # 搴旂敤淇℃伅
  device_info_plus: ^11.3.0 # 璁惧淇℃伅
  flutter_windowmanager:
    path: third-party/tool/flutter_windowmanager # 闃叉埅鍥?
  share_plus: ^10.1.4 # 鍒嗕韩
  url_launcher: ^6.3.0 # URL璺宠浆
  app_links: ^6.1.4 # 搴旂敤URI
  flutter_displaymode: ^0.6.0 # 璁剧疆鍒锋柊鐜?
  image_gallery_saver:
    path: third-party/tool/image_gallery_saver # 淇濆瓨鍥剧墖鍒扮浉鍐?
  lucide_icons:
    path: third-party/widget/lucide_icons
  permission_handler: ^11.3.1 # 鏉冮檺绠＄悊
  install_plugin: ^2.1.0 # 瀹夎APP
  flutter_local_notifications: ^17.2.1+2 # 閫氱煡
  hotkey_manager: ^0.2.3 # 鐑敭
  # 瀛樺偍/缃戠粶
  path:
  http: ^1.2.1
  logger: ^2.4.0 # 鏃ュ織
  dio: ^5.4.3+1 # 缃戠粶璇锋眰
  hive: ^2.2.3 # 杞婚噺瀛樺偍
  path_provider: ^2.0.12
  sqflite: ^2.3.3+1 # SQLite鏁版嵁搴?
  file_picker: ^8.3.1 # 鏂囦欢閫夋嫨
  pointycastle: 3.9.1
  dio_cache_interceptor: ^3.5.0 # dio缂撳瓨
  dio_cookie_manager: ^3.1.1 # dio cookie绠＄悊
  cached_network_image: ^3.2.1 # 缃戠粶鍥剧墖缂撳瓨
  flutter_cache_manager: ^3.3.1 # 缂撳瓨绠＄悊
  process_run: ^1.0.0+1 # 杩愯
  # 宸ュ叿
  intl:
  intl_utils: ^2.8.9
  html: ^0.15.0
  tuple: ^2.0.0 # 鍏冪粍
  crypto: ^3.0.3 # 鍔犲瘑
  encrypt: ^5.0.3 # 鍔犲瘑
  dart_sm: ^0.1.5 # 鍔犲瘑
  flutter_native_splash: ^2.4.1 # Splash灞?
  palette_generator: ^0.3.3+3 # 鑾峰彇涓昏壊璋?
  vector_math: ^2.1.4
  # 骞冲彴閫傞厤
  responsive_builder: ^0.7.1 # 鍝嶅簲寮忓竷灞€
  tray_manager: ^0.2.3 # 鎵樼洏鍥炬爣
  window_manager: ^0.4.3 # 绐楀彛绠＄悊
  restart_app: ^1.2.1 # 閲嶅惎APP
  launch_at_startup: ^0.3.1 # 寮€鏈哄惎鍔?
  local_notifier: ^0.1.6 # 鏈湴閫氱煡
  protocol_handler: ^0.2.0 # 鍗忚澶勭悊
#  desktop_multi_window: # 澶氱獥鍙?
#    path: third-party/desktop_multi_window
#  window_size: # 绐楀彛澶у皬
#    git:
#      url: https://github.com/google/flutter-desktop-embedding.git
#      path: plugins/window_size
#      ref: a738913c8ce2c9f47515382d40827e794a334274
#  texture_rgba_renderer: ^0.0.16 # 绾圭悊娓叉煋

dependency_overrides:
  webview_flutter_android: 3.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  msix: ^3.16.7
  sqflite_common_ffi: ^2.3.3

msix_config:
  display_name: Loftify
  publisher_display_name: Cloudchewie
  identity_name: com.cloudchewie.loftify
  msix_version: 1.8.0.0
  logo_path: D:\Repositories\Loftify\assets\logo-transparent-big.ico
  #  trim_logo: false
  output_path: D:\Ruida\Downloads
  output_name: Loftify
  build_windows: false
  capabilities: internetClient
  certificate_path: D:\Repositories\Loftify\certificate\loftify.pfx
  certificate_password: CLOUDCHEWIEloftify@123

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: "assets/logo-transparent.png"
  android: true
  ios: true

  android_12:
    image: assets/logo-transparent.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/logo-transparent.png
    icon_background_color_dark: "#121212"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icon/
    - assets/illust/
    - assets/mess/
    - assets/avatar.png
    - assets/logo.png
    - assets/logo.svg
    - assets/logo-transparent.png
    - assets/logo-transparent-big.png
    - assets/logo-transparent-big.ico